#!/usr/bin/env python3
"""Regenerate snapforge/platform.py from the snaps installed on this machine."""

import re
import textwrap
from pathlib import Path

# Only what a DT_NEEDED can actually name: lib*.so or lib*.so.N.
SONAME = re.compile(r"^(?:lib|ld-).+\.so(\.\d+)?$")

HEAD = '''"""What the base and the gnome extension supply before anything stages."""

# Generated by tools_platform_gen.py off the snaps installed where it ran.

BASE_SNAP = "{base_snap}"
GNOME_SNAP = "{gnome_snap}"

'''

BASE_SNAP = "core24"
GNOME_SNAP = "gnome-46-2404"


def sonames(root):
    """Every shared library one snap supplies, by the name others ask for."""
    found = set()
    for sub in ("usr/lib", "lib"):
        where = Path(root) / sub
        if where.is_dir():
            found |= {f.name for f in where.rglob("*.so*") if SONAME.match(f.name)}
    return found


def renamed_t64():
    """Packages noble renamed for 64-bit time_t, read off this host's dpkg."""
    found = set()
    for listing in Path("/var/lib/dpkg/info").glob("*t64*.list"):
        name = listing.name[: -len(".list")].split(":")[0]
        if name.endswith("t64"):
            found.add(name[: -len("t64")])
    return found


# Hand-checked: the convention gets these wrong and desktops need them.
KNOWN = {
    "libnss3.so": "libnss3", "libnssutil3.so": "libnss3",
    "libsmime3.so": "libnss3", "libssl3.so": "libnss3",
    "libnspr4.so": "libnspr4", "libplc4.so": "libnspr4",
    "libplds4.so": "libnspr4",
    "libGL.so.1": "libgl1", "libEGL.so.1": "libegl1",
    "libGLESv2.so.2": "libgles2", "libGLESv1_CM.so.1": "libgles1",
    "libGLX.so.0": "libglx0", "libGLdispatch.so.0": "libglvnd0",
    "libOpenGL.so.0": "libopengl0", "libGLU.so.1": "libglu1-mesa",
    "libasound.so.2": "libasound2t64", "libudev.so.1": "libudev1",
    "libva.so.2": "libva2", "libva-drm.so.2": "libva-drm2",
    "libva-x11.so.2": "libva-x11-2", "libvdpau.so.1": "libvdpau1",
    "libappindicator3.so.1": "libappindicator3-1",
    "libayatana-appindicator3.so.1": "libayatana-appindicator3-1",
    "libindicator3.so.7": "libindicator3-7",
    "libdbusmenu-glib.so.4": "libdbusmenu-glib4",
    "libdbusmenu-gtk3.so.4": "libdbusmenu-gtk3-4",
}

# The host driver supplies these, so staging one would pin a version.
FROM_THE_HOST = frozenset("""
libcuda.so.1 libnvidia-ml.so.1 libnvcuvid.so.1 libGLX_nvidia.so.0
libEGL_nvidia.so.0 libGLESv2_nvidia.so.2 libvulkan_radeon.so
libvulkan_intel.so libnvoptix.so.1
""".split())


def owners():
    """soname -> the package that ships it, off this host's dpkg lists."""
    found = {}
    for listing in Path("/var/lib/dpkg/info").glob("*.list"):
        package = listing.name[: -len(".list")].split(":")[0]
        try:
            text = listing.read_text(errors="replace")
        except OSError:
            continue
        for line in text.splitlines():
            name = line.rsplit("/", 1)[-1]
            if SONAME.match(name):
                found.setdefault(name, package)
    return found


def conventions(soname):
    """The Debian names a soname implies: libfoo.so.2 is libfoo2, or libfoo-2."""
    parts = re.match(r"^(.+?)\.so\.(\d+)$", soname)
    if not parts:
        return ()
    stem = parts.group(1).lower().replace("_", "-")
    return (stem + parts.group(2), stem + "-" + parts.group(2))


def proven_packages():
    """Package names from recipes that build, so noble is known to have them."""
    found = set()
    root = Path("~/Development/github/snapkit/snap-db").expanduser()
    for recipe in root.glob("*/snap/snapcraft.yaml"):
        text = recipe.read_text()
        for head in re.finditer(r"(?m)^(\s*)stage-packages:\s*$", text):
            depth = len(head.group(1))
            for line in text[head.end():].splitlines():
                stripped = line.lstrip()
                # A blank line or a comment is still inside the block.
                if not stripped or stripped.startswith("#"):
                    continue
                if len(line) - len(stripped) <= depth \
                        or not stripped.startswith("-"):
                    break
                found.add(stripped[1:].strip())
    return found


def package_table(base):
    """soname -> package, only where something other than a guess says so."""
    owned = owners()
    table = dict(KNOWN)
    # A name a working recipe stages is a name noble really has.
    proven = proven_packages()
    for soname, package in owned.items():
        if package in proven:
            table.setdefault(soname, package)
    # Where dpkg confirms the convention, the name follows from the soname.
    for soname, package in owned.items():
        stem = package[: -len("t64")] if package.endswith("t64") else package
        if stem in conventions(soname):
            table.setdefault(soname, package)
    return {s: p for s, p in sorted(table.items())
            if s not in base and s not in FROM_THE_HOST}


def supplied_packages(base, gnome):
    """Packages whose every library the platform already has, so staging is moot."""
    by_package = {}
    for listing in Path("/var/lib/dpkg/info").glob("*.list"):
        package = listing.name[: -len(".list")].split(":")[0]
        try:
            text = listing.read_text(errors="replace")
        except OSError:
            continue
        names = {line.rsplit("/", 1)[-1] for line in text.splitlines()}
        libs = {n for n in names if SONAME.match(n)}
        if libs:
            by_package.setdefault(package, set()).update(libs)
    in_base = {p for p, libs in by_package.items() if libs <= base}
    in_gnome = {p for p, libs in by_package.items() if libs <= (base | gnome)}
    # Both spellings, because a record may name either side of the rename.
    for found in (in_base, in_gnome):
        found |= {p[: -len("t64")] for p in list(found) if p.endswith("t64")}
    return in_base, in_gnome - in_base


def block(name, items, why):
    """One frozenset, wrapped so the file stays something a person can read."""
    body = "\n".join(textwrap.wrap(" ".join(sorted(items)), 74))
    return f'# {why}\n{name} = frozenset("""\n{body}\n""".split())\n\n'


def main():
    base = sonames(f"/snap/{BASE_SNAP}/current")
    gnome = sonames(f"/snap/{GNOME_SNAP}/current") - base
    t64 = renamed_t64()
    if not base or not gnome:
        raise SystemExit(f"install {BASE_SNAP} and {GNOME_SNAP} first")

    text = HEAD.format(base_snap=BASE_SNAP, gnome_snap=GNOME_SNAP)
    text += block("BASE", base,
                  "Sonames the base supplies, so nothing ever needs to stage them.")
    text += block("GNOME", gnome,
                  "And what the gnome extension adds, for the apps that use it.")
    text += block("RENAMED_T64", t64,
                  "noble renamed these for 64-bit time_t: libasound2 is libasound2t64.")

    in_base, in_gnome = supplied_packages(base, gnome)
    text += block("SUPPLIED_BY_BASE", in_base,
                  "Packages the base already covers, whatever a Depends: says.")
    text += block("SUPPLIED_BY_GNOME", in_gnome,
                  "And the ones the gnome extension covers, for apps that use it.")

    table = package_table(base)
    rows = "\n".join(f'    "{s}": "{p}",' for s, p in table.items())
    text += block("FROM_THE_HOST", FROM_THE_HOST,
                  "Driver libraries an interface supplies, never staged.")
    text += ("# Which package ships a soname, where evidence says so, not a guess.\n"
             f"PACKAGE_OF = {{\n{rows}\n}}\n")
    Path(__file__).parent.joinpath("snapforge/platform.py").write_text(text)
    print(f"base {len(base)}, gnome {len(gnome)}, t64 {len(t64)}, "
          f"package_of {len(table)}, supplied {len(in_base)}+{len(in_gnome)}")


if __name__ == "__main__":
    main()
