"""What the base and the gnome extension supply before anything stages."""

# Generated by tools_platform_gen.py off the snaps installed where it ran.

BASE_SNAP = "core24"
GNOME_SNAP = "gnome-46-2404"

# Sonames the base supplies, so nothing ever needs to stage them.
BASE = frozenset("""
ld-linux-x86-64.so.2 ld-linux.so.2 libBrokenLocale.so.1 libCNS.so libGB.so
libISOIR165.so libJIS.so libJISX0213.so libKSC.so libacl.so.1 libanl.so.1
libapparmor.so.1 libargon2.so.1 libarpt_mangle.so libassuan.so.0
libattr.so.1 libaudit.so.1 libblkid.so.1 libbpf.so.1 libbrotlicommon.so.1
libbrotlidec.so.1 libbrotlienc.so.1 libbsd.so.0 libbz2.so.1 libc.so.6
libc_malloc_debug.so.0 libcap-ng.so.0 libcap.so.2 libcom_err.so.2
libcrack.so.2 libcrypt.so.1 libcrypto.so.3 libcryptsetup-token-systemd-
fido2.so libcryptsetup-token-systemd-pkcs11.so libcryptsetup-token-
systemd-tpm2.so libcryptsetup.so.12 libdb-5.3.so libdbus-1.so.3
libdebconfclient.so.0 libdl.so.2 libdrm.so.2 libdrop_ambient.so.0
libduktape.so.207 libe2p.so.2 libeac.so.3 libebt_802_3.so libebt_among.so
libebt_arp.so libebt_arpreply.so libebt_dnat.so libebt_ip.so libebt_ip6.so
libebt_log.so libebt_mark.so libebt_mark_m.so libebt_nflog.so
libebt_pkttype.so libebt_redirect.so libebt_snat.so libebt_stp.so
libebt_vlan.so libedit.so.2 libelf-0.190.so libelf.so.1 libevdev.so.2
libevent-2.1.so.7 libexpat.so.1 libexpatw.so.1 libext2fs.so.2
libfdisk.so.1 libffi.so.8 libfido2.so.1 libformw.so.6 libfreetype.so.6
libgcc_s.so.1 libgcrypt.so.20 libgio-2.0.so.0 libglib-2.0.so.0
libgmodule-2.0.so.0 libgmp.so.10 libgnutls-dane.so.0 libgnutls.so.30
libgobject-2.0.so.0 libgpg-error.so.0 libgssapi_krb5.so.2
libgthread-2.0.so.0 libhistory.so.8 libhogweed.so.6 libidn2.so.0
libinproctrace.so libip4tc.so.2 libip6t_DNPT.so libip6t_HL.so
libip6t_NETMAP.so libip6t_REJECT.so libip6t_SNPT.so libip6t_ah.so
libip6t_dst.so libip6t_eui64.so libip6t_frag.so libip6t_hbh.so
libip6t_hl.so libip6t_icmp6.so libip6t_ipv6header.so libip6t_mh.so
libip6t_rt.so libip6t_srh.so libip6tc.so.2 libipt_CLUSTERIP.so
libipt_ECN.so libipt_NETMAP.so libipt_REJECT.so libipt_TTL.so
libipt_ULOG.so libipt_ah.so libipt_icmp.so libipt_realm.so libipt_ttl.so
libjson-c.so.5 libk5crypto.so.3 libkeyutils.so.1 libkmod.so.2 libkrb5.so.3
libkrb5support.so.0 liblz4.so.1 liblzma.so.5 liblzo2.so.2 libm.so.6
libmagic.so.1 libmd.so.0 libmemusage.so libmenuw.so.6 libmnl.so.0
libmount.so.1 libmvec.so.1 libncursesw.so.6 libnetfilter_conntrack.so.3
libnetplan.so.1 libnettle.so.8 libnfnetlink.so.0 libnftnl.so.11
libnl-3.so.200 libnl-genl-3.so.200 libnl-route-3.so.200 libnpth.so.0
libnsl.so.1 libnss_compat.so.2 libnss_dns.so.2 libnss_extrausers.so.2
libnss_files.so.2 libnss_hesiod.so.2 libnss_mdns4_minimal.so.2
libopensc.so.11 libopts.so.25 libp11-kit.so.0 libp11.so.3 libpam.so.0
libpam_misc.so.0 libpamc.so.0 libpanelw.so.6 libpciaccess.so.0
libpcprofile.so libpcre2-8.so.0 libpcsclite.so.1 libpkcs11.so libply-boot-
client.so.5 libply-splash-core.so.5 libply-splash-graphics.so.5
libply.so.5 libpng16.so.16 libpolkit-agent-1.so.0 libpolkit-gobject-1.so.0
libpopt.so.0 libproc2.so.0 libpsx.so.2 libpthread.so.0 libpwquality.so.1
libreadline.so.8 libresolv.so.2 librt.so.1 libseccomp.so.2 libselinux.so.1
libsemanage.so.2 libsepol.so.2 libsmartcols.so.1 libsqlite3.so.0
libss.so.2 libssl.so.3 libstdc++.so.6 libsystemd-core-255.so libsystemd-
shared-255.so libsystemd.so.0 libtasn1.so.6 libthread_db.so.1 libtic.so.6
libtinfo.so.6 libtirpc.so.3 libudev.so.1 libunistring.so.5 libutil.so.1
libuuid.so.1 libwrap.so.0 libxkbcommon.so.0 libxt_AUDIT.so
libxt_CHECKSUM.so libxt_CLASSIFY.so libxt_CONNMARK.so libxt_CONNSECMARK.so
libxt_CT.so libxt_DNAT.so libxt_DSCP.so libxt_HMARK.so libxt_IDLETIMER.so
libxt_LED.so libxt_LOG.so libxt_MARK.so libxt_MASQUERADE.so libxt_NAT.so
libxt_NFLOG.so libxt_NFQUEUE.so libxt_NOTRACK.so libxt_RATEEST.so
libxt_REDIRECT.so libxt_SECMARK.so libxt_SET.so libxt_SNAT.so
libxt_SYNPROXY.so libxt_TCPMSS.so libxt_TCPOPTSTRIP.so libxt_TEE.so
libxt_TOS.so libxt_TPROXY.so libxt_TRACE.so libxt_addrtype.so libxt_bpf.so
libxt_cgroup.so libxt_cluster.so libxt_comment.so libxt_connbytes.so
libxt_connlabel.so libxt_connlimit.so libxt_connmark.so libxt_conntrack.so
libxt_cpu.so libxt_dccp.so libxt_devgroup.so libxt_dscp.so libxt_ecn.so
libxt_esp.so libxt_hashlimit.so libxt_helper.so libxt_ipcomp.so
libxt_iprange.so libxt_ipvs.so libxt_length.so libxt_limit.so libxt_mac.so
libxt_mark.so libxt_multiport.so libxt_nfacct.so libxt_osf.so
libxt_owner.so libxt_physdev.so libxt_pkttype.so libxt_policy.so
libxt_quota.so libxt_rateest.so libxt_recent.so libxt_rpfilter.so
libxt_sctp.so libxt_set.so libxt_socket.so libxt_standard.so
libxt_state.so libxt_statistic.so libxt_string.so libxt_tcp.so
libxt_tcpmss.so libxt_time.so libxt_tos.so libxt_u32.so libxt_udp.so
libxtables.so.12 libxxhash.so.0 libyaml-0.so.2 libz.so.1 libzstd.so.1
""".split())

# And what the gnome extension adds, for the apps that use it.
GNOME = frozenset("""
libBrokenLocale.so libFLAC.so.12 libGLESv1_CM.so libGLESv1_CM.so.1
libGLU.so libGLU.so.1 libICE.so libICE.so.6 libIex-3_1.so libIex-3_1.so.30
libIex.so libIlmThread-3_1.so libIlmThread-3_1.so.30 libIlmThread.so
libImath-3_1.so libImath-3_1.so.29 libImath.so libLerc.so libLerc.so.4
libOpenCL.so.1 libOpenEXR-3_1.so libOpenEXR-3_1.so.30 libOpenEXR.so
libOpenEXRCore-3_1.so libOpenEXRCore-3_1.so.30 libOpenEXRCore.so
libOpenEXRUtil-3_1.so libOpenEXRUtil-3_1.so.30 libOpenEXRUtil.so
libOpenGL.so libOpenGL.so.0 libQt5Core.so.5 libQt5DBus.so.5
libQt5EglFSDeviceIntegration.so.5 libQt5EglFsKmsSupport.so.5
libQt5Gui.so.5 libQt5Network.so.5 libQt5OpenGL.so.5 libQt5Test.so.5
libQt5Widgets.so.5 libQt5XcbQpa.so.5 libSM.so libSM.so.6 libSvtAv1Enc.so.1
libXNVCtrl.so.0 libXcomposite.so libXcomposite.so.1 libXcursor.so
libXcursor.so.1 libXft.so libXft.so.2 libXi.so libXi.so.6 libXinerama.so
libXinerama.so.1 libXpm.so.4 libXrandr.so libXrandr.so.2 libXrender.so
libXrender.so.1 libXss.so.1 libXt.so libXt.so.6 libXtst.so libXtst.so.6
libaa.so.1 libadrg.so libadwaita-1.so libadwaita-1.so.0 libaec.so.0
libamd_comgr.so.2 libamdhip64.so.5 libanl.so libaom.so libaom.so.3
libappstream-glib.so.8 libappstream.so libappstream.so.5 libarchive.so.13
libarmadillo.so.12 libarpack.so.2 libasan.so libasan.so.8 libasound.so.2
libaspell.so.15 libasyncns.so.0 libatk-1.0.so libatk-1.0.so.0 libatk-
bridge-2.0.so libatk-bridge-2.0.so.0 libatk-bridge.so libatkmm-2.36.so
libatkmm-2.36.so.1 libatomic.so libatomic.so.1 libatspi.so libatspi.so.0
libavahi-client.so.3 libavahi-common.so.3 libavc1394.so.0 libavcodec.so
libavcodec.so.60 libavformat.so libavformat.so.60 libavutil.so
libavutil.so.58 libayatana-appindicator3.so libayatana-appindicator3.so.1
libayatana-ido3-0.4.so libayatana-ido3-0.4.so.0 libayatana-indicator3.so
libayatana-indicator3.so.7 libbfd-2.42-system.so libblas.so.3 libblkid.so
libblosc.so.1 libbluray.so.2 libbnxt_re-rdmav34.so libbrotlicommon.so
libbrotlidec.so libbrotlienc.so libbz2.so libc.so libc_malloc_debug.so
libcaca++.so.0 libcaca.so.0 libcairo-fdr.so libcairo-gobject.so libcairo-
gobject.so.2 libcairo-script-interpreter.so libcairo-script-
interpreter.so.2 libcairo-trace.so libcairo.so libcairo.so.2
libcairomm-1.16.so libcairomm-1.16.so.1 libcanberra-alsa.so libcanberra-
gtk-module.so libcanberra-gtk3-module.so libcanberra-gtk3.so libcanberra-
gtk3.so.0 libcanberra-pulse.so libcanberra.so libcanberra.so.0 libcc1.so
libcc1.so.0 libcc1plugin.so libcc1plugin.so.0 libcdda_interface.so.0
libcdda_paranoia.so.0 libcdt.so libcdt.so.5 libcfitsio.so.10 libcgraph.so
libcgraph.so.6 libcharls.so.2 libchromaprint.so.1 libcjson.so.1
libcjson_utils.so.1 libclutter-1.0.so libclutter-1.0.so.0 libclutter-
gtk-1.0.so libclutter-gtk-1.0.so.0 libcogl-gles2.so libcogl-gles2.so.20
libcogl-pango.so libcogl-pango.so.20 libcogl-path.so libcogl-path.so.20
libcogl.so libcogl.so.20 libcolord.so.2 libcolordprivate.so.2
libcom_err.so libcomposeplatforminputcontextplugin.so libcp1plugin.so
libcp1plugin.so.0 libcrypt.so libctf-nobfd.so.0 libctf.so.0 libcups.so.2
libcurl-gnutls.so.3 libcurl-gnutls.so.4 libcurl.so libcurl.so.4
libcxgb4-rdmav34.so libdatrie.so libdatrie.so.1 libdav1d.so libdav1d.so.7
libdazzle-1.0.so libdazzle-1.0.so.0 libdbus-1.so libdbus-glib-1.so
libdbus-glib-1.so.2 libdbusmenu-glib.so libdbusmenu-glib.so.4 libdbusmenu-
gtk3.so libdbusmenu-gtk3.so.4 libdc1394.so libdc1394.so.25 libdconf.so.1
libdconfsettings.so libde265.so libde265.so.0 libdee-1.0.so
libdee-1.0.so.4 libdeflate.so libdeflate.so.0 libdep.so libdfalt.so.0
libdouble-conversion.so.3 libdv.so.4 libdw-0.190.so libdw.so libdw.so.1
libecs_tcl.so libefa-rdmav34.so libefa.so.1 libelf.so libenchant-2.so
libenchant-2.so.2 libepoxy.so libepoxy.so.0 liberdma-rdmav34.so
libevdev.so libevent_core-2.1.so.7 libevent_pthreads-2.1.so.7 libexif.so
libexif.so.12 libexpat.so libexpatw.so libexslt.so.0 libfabric.so.1
libfcitx-gclient.so.1 libfcitx-utils.so.0 libffi.so libfontconfig.so
libfontconfig.so.1 libform.so.6 libfreebl3.so libfreeblpriv3.so
libfreetype.so libfreexl.so.1 libfribidi.so libfribidi.so.0 libfyba.so.0
libfygm.so.0 libfyut.so.0 libgailutil-3.so libgailutil-3.so.0 libgcc_s.so
libgck-1.so libgck-1.so.0 libgcr-base-3.so libgcr-base-3.so.1 libgcr-
ui-3.so libgcr-ui-3.so.1 libgcrypt.so libgd.so.3 libgdal.so libgdal.so.34
libgdbm.so.6 libgdbm_compat.so.4 libgdcmCommon.so libgdcmDICT.so
libgdcmDSED.so libgdcmIOD.so libgdcmMEXD.so libgdcmMSFF.so
libgdcmjpeg12.so libgdcmjpeg16.so libgdcmjpeg8.so libgdk-3.so
libgdk-3.so.0 libgdk-x11-2.0.so.0 libgdk_pixbuf-2.0.so
libgdk_pixbuf-2.0.so.0 libgee-0.8.so libgee-0.8.so.2 libgeocode-glib-2.so
libgeocode-glib-2.so.0 libgeos_c.so.1 libgeotiff.so.5
libgettextlib-0.21.so libgettextsrc-0.21.so libgfortran.so.5 libgif.so.7
libgio-2.0.so libgiognomeproxy.so libgiognutls.so libgiolibproxy.so
libgiomm-2.68.so libgiomm-2.68.so.1 libgirepository-1.0.so
libgirepository-1.0.so.1 libgirepository-2.0.so libgirepository-2.0.so.0
libgit2-glib-1.0.so.0 libgjs.so libgjs.so.0 libgl_plugin.so
libgl_plugin.so.0 libglib-2.0.so libglibmm-2.68.so libglibmm-2.68.so.1
libglibmm_generate_extra_defs-2.68.so
libglibmm_generate_extra_defs-2.68.so.1 libglut.so libgme.so.0
libgmodule-2.0.so libgmp.so libgmpxx.so libgmpxx.so.4 libgnome-bg-4.so
libgnome-bg-4.so.2 libgnome-desktop-3.so libgnome-desktop-3.so.20
libgnome-desktop-4.so libgnome-desktop-4.so.2 libgnome-games-support-2.so
libgnome-games-support-2.so.4 libgnome-rr-4.so libgnome-rr-4.so.2
libgnutls-dane.so libgnutls-openssl.so libgnutls-openssl.so.27
libgnutls.so libgoa-1.0.so.0 libgobject-2.0.so libgomp.so libgomp.so.1
libgp-collector.so libgp-collectorAPI.so libgp-heap.so libgp-iotrace.so
libgp-sync.so libgpg-error.so libgphoto2.so libgphoto2.so.6
libgphoto2_port.so libgphoto2_port.so.12 libgpm.so.2 libgprofng.so.0
libgraphene-1.0.so libgraphene-1.0.so.0 libgraphite2.so libgraphite2.so.3
libgsm.so.1 libgsound.so libgsound.so.0 libgspell-1.so libgspell-1.so.2
libgssapi_krb5.so libgssdp-1.6.so.0 libgssrpc.so libgssrpc.so.4
libgst1394.so libgstaasink.so libgstadaptivedemux-1.0.so
libgstadaptivedemux-1.0.so.0 libgstadaptivedemux2.so libgstadder.so
libgstalaw.so libgstallocators-1.0.so libgstallocators-1.0.so.0
libgstalpha.so libgstalphacolor.so libgstanalytics-1.0.so
libgstanalytics-1.0.so.0 libgstapetag.so libgstapp-1.0.so
libgstapp-1.0.so.0 libgstapp.so libgstaudio-1.0.so libgstaudio-1.0.so.0
libgstaudioconvert.so libgstaudiofx.so libgstaudiomixer.so
libgstaudioparsers.so libgstaudiorate.so libgstaudioresample.so
libgstaudiotestsrc.so libgstauparse.so libgstautodetect.so libgstavi.so
libgstbadaudio-1.0.so libgstbadaudio-1.0.so.0 libgstbase-1.0.so
libgstbase-1.0.so.0 libgstbasecamerabinsrc-1.0.so
libgstbasecamerabinsrc-1.0.so.0 libgstbasedebug.so libgstcacasink.so
libgstcairo.so libgstcamerabin.so libgstcdparanoia.so libgstcheck-1.0.so
libgstcheck-1.0.so.0 libgstcodecparsers-1.0.so libgstcodecparsers-1.0.so.0
libgstcodecs-1.0.so libgstcodecs-1.0.so.0 libgstcompositor.so
libgstcontroller-1.0.so libgstcontroller-1.0.so.0 libgstcoreelements.so
libgstcoretracers.so libgstcuda-1.0.so libgstcuda-1.0.so.0 libgstcutter.so
libgstdebug.so libgstdeinterlace.so libgstdsd.so libgstdtmf.so libgstdv.so
libgstdxva-1.0.so libgstdxva-1.0.so.0 libgsteffectv.so libgstencoding.so
libgstequalizer.so libgstfft-1.0.so libgstfft-1.0.so.0 libgstflac.so
libgstflv.so libgstflxdec.so libgstgdkpixbuf.so libgstgio.so
libgstgl-1.0.so libgstgl-1.0.so.0 libgstgoom.so libgstgoom2k1.so
libgsticydemux.so libgstid3demux.so libgstimagefreeze.so
libgstinsertbin-1.0.so libgstinsertbin-1.0.so.0 libgstinterleave.so
libgstisoff-1.0.so libgstisoff-1.0.so.0 libgstisomp4.so libgstjack.so
libgstjpeg.so libgstjpegformat.so libgstlame.so libgstlevel.so
libgstlibvisual.so libgstmatroska.so libgstmonoscope.so
libgstmpegts-1.0.so libgstmpegts-1.0.so.0 libgstmpg123.so libgstmse-1.0.so
libgstmse-1.0.so.0 libgstmulaw.so libgstmultifile.so libgstmultipart.so
libgstnavigationtest.so libgstnet-1.0.so libgstnet-1.0.so.0 libgstogg.so
libgstopencv-1.0.so libgstopencv-1.0.so.0 libgstopengl.so libgstopus.so
libgstoss4.so libgstossaudio.so libgstoverlaycomposition.so
libgstpbtypes.so libgstpbutils-1.0.so libgstpbutils-1.0.so.0
libgstphotography-1.0.so libgstphotography-1.0.so.0 libgstpipewire.so
libgstplay-1.0.so libgstplay-1.0.so.0 libgstplayback.so
libgstplayer-1.0.so libgstplayer-1.0.so.0 libgstpng.so libgstpulseaudio.so
libgstrawparse.so libgstreamer-1.0.so libgstreamer-1.0.so.0
libgstreplaygain.so libgstriff-1.0.so libgstriff-1.0.so.0 libgstrtp-1.0.so
libgstrtp-1.0.so.0 libgstrtp.so libgstrtpmanager.so libgstrtsp-1.0.so
libgstrtsp-1.0.so.0 libgstrtsp.so libgstsctp-1.0.so libgstsctp-1.0.so.0
libgstsdp-1.0.so libgstsdp-1.0.so.0 libgstshapewipe.so libgstshout2.so
libgstsmpte.so libgstsoup.so libgstspectrum.so libgstspeex.so
libgstsubparse.so libgsttag-1.0.so libgsttag-1.0.so.0 libgsttaglib.so
libgsttcp.so libgsttheora.so libgsttranscoder-1.0.so
libgsttranscoder-1.0.so.0 libgsttwolame.so libgsttypefindfunctions.so
libgstudp.so libgsturidownloader-1.0.so libgsturidownloader-1.0.so.0
libgstva-1.0.so libgstva-1.0.so.0 libgstvideo-1.0.so libgstvideo-1.0.so.0
libgstvideo4linux2.so libgstvideobox.so libgstvideoconvertscale.so
libgstvideocrop.so libgstvideofilter.so libgstvideomixer.so
libgstvideorate.so libgstvideotestsrc.so libgstvolume.so libgstvorbis.so
libgstvpx.so libgstvulkan-1.0.so libgstvulkan-1.0.so.0 libgstwavenc.so
libgstwavpack.so libgstwavparse.so libgstwayland-1.0.so
libgstwayland-1.0.so.0 libgstwebrtc-1.0.so libgstwebrtc-1.0.so.0
libgstwebrtcnice-1.0.so libgstwebrtcnice-1.0.so.0 libgstximagesrc.so
libgstxingmux.so libgsty4menc.so libgthread-2.0.so libgtk-3.so
libgtk-3.so.0 libgtk-4.so libgtk-4.so.1 libgtk-x11-2.0.so.0
libgtk3-nocsd.so.0 libgtkmm-4.0.so libgtkmm-4.0.so.0
libgtksourceview-3.0.so.1 libgtksourceview-5.so libgtksourceview-5.so.0
libgts-0.7.so.5 libgucharmap_2_90.so.7 libgudev-1.0.so libgudev-1.0.so.0
libgupnp-1.6.so.0 libgupnp-igd-1.6.so.0 libgvc.so libgvc.so.6
libgvplugin_core.so libgvplugin_core.so.6 libgvplugin_dot_layout.so
libgvplugin_dot_layout.so.6 libgvplugin_gd.so libgvplugin_gd.so.6
libgvplugin_gdk.so libgvplugin_gdk.so.6 libgvplugin_gtk.so
libgvplugin_gtk.so.6 libgvplugin_neato_layout.so
libgvplugin_neato_layout.so.6 libgvplugin_pango.so libgvplugin_pango.so.6
libgvplugin_rsvg.so libgvplugin_rsvg.so.6 libgvplugin_visio.so
libgvplugin_visio.so.6 libgvplugin_webp.so libgvplugin_webp.so.6
libgvplugin_xlib.so libgvplugin_xlib.so.6 libgvpr.so libgvpr.so.2
libgweather-4.so libgweather-4.so.0 libhandy-1.so libhandy-1.so.0
libharfbuzz-cairo.so libharfbuzz-cairo.so.0 libharfbuzz-gobject.so
libharfbuzz-gobject.so.0 libharfbuzz-icu.so libharfbuzz-icu.so.0
libharfbuzz-subset.so libharfbuzz-subset.so.0 libharfbuzz.so
libharfbuzz.so.0 libhdf5_serial.so.103 libhdf5_serial_hl.so.100 libheif-
aomdec.so libheif.so libheif.so.1 libhelloworld.so libhfi1verbs-rdmav34.so
libhns-rdmav34.so libhogweed.so libhsa-runtime64.so.1 libhsakmt.so.1
libhunspell-1.7.so.0 libhwasan.so libhwasan.so.0 libhwloc.so.15
libhwy.so.1 libhwy_contrib.so.1 libhwy_test.so.1 libhyphen.so.0
libibus-1.0.so.5 libibusplatforminputcontextplugin.so libibverbs.so.1
libidn2.so libiec61883.so.0 libinfinipath.so.4 libinput.so libinput.so.10
libipathverbs-rdmav34.so libirdma-rdmav34.so libisl.so.23 libitm.so
libitm.so.1 libjansson.so.4 libjavascriptcoregtk-4.1.so
libjavascriptcoregtk-4.1.so.0 libjbig.so libjbig.so.0 libjpeg.so
libjpeg.so.8 libjson-glib-1.0.so libjson-glib-1.0.so.0 libjsoncpp.so.25
libk5crypto.so libkadm5clnt.so libkadm5clnt_mit.so libkadm5clnt_mit.so.12
libkadm5srv.so libkadm5srv_mit.so libkadm5srv_mit.so.12 libkdb5.so
libkdb5.so.10 libkmlbase.so.1 libkmldom.so.1 libkmlengine.so.1 libkrb5.so
libkrb5support.so liblab_gamut.so liblab_gamut.so.1 liblapack.so.3
liblber.so.2 liblcms2.so liblcms2.so.2 libldap.so.2 liblept.so.5
liblsan.so liblsan.so.0 libltdl.so libltdl.so.7 liblto_plugin.so
liblzma.so liblzo2.so libm.so libmana-rdmav34.so libmana.so.1
libmanette-0.2.so.0 libmbedcrypto.so.7 libmca_common_monitoring.so.50
libmca_common_ofi.so.10 libmca_common_ompio.so.41 libmca_common_sm.so.40
libmca_common_ucx.so.40 libmca_common_verbs.so.40 libmd4c.so.0 libmedia-
gstreamer.so libmenu.so.6 libmfhdfalt.so.0 libminizip.so.1
libmlx4-rdmav34.so libmlx4.so.1 libmlx5-rdmav34.so libmlx5.so.1
libmount.so libmozjs-115.so libmozjs-115.so.0 libmp3lame.so.0 libmpc.so.3
libmpfr.so.6 libmpg123.so.0 libmpi.so.40 libmpi_cxx.so.40
libmpi_java.so.40 libmpi_mpifh-gfortran.so.40 libmpi_mpifh.so.40
libmpi_usempi_ignore_tkr-gfortran.so.40 libmpi_usempi_ignore_tkr.so.40
libmpi_usempif08-gfortran.so.40 libmpi_usempif08.so.40 libmtdev.so.1
libmthca-rdmav34.so libmunge.so.2 libmvec.so libmysqlclient.so.21
libncurses.so.6 libnetcdf.so.19 libnettle.so libnghttp2.so
libnghttp2.so.14 libnice.so.10 libnorm.so.1 libnotify.so libnotify.so.4
libnsl.so libnsl.so.2 libnspr4.so libnss3.so libnss_compat.so
libnss_hesiod.so libnssckbi.so libnssdbm3.so libnssutil3.so libnuma.so.1
libocrdma-rdmav34.so libodbc.so.2 libodbcinst.so.2 libogdi.so.4
libogg.so.0 libompi_dbg_msgq.so libompitrace.so.40
libopcodes-2.42-system.so libopen-pal.so.40 libopen-rte.so.40
libopencv_alphamat.so libopencv_alphamat.so.406 libopencv_aruco.so
libopencv_aruco.so.406 libopencv_barcode.so libopencv_barcode.so.406
libopencv_bgsegm.so libopencv_bgsegm.so.406 libopencv_bioinspired.so
libopencv_bioinspired.so.406 libopencv_calib3d.so libopencv_calib3d.so.406
libopencv_ccalib.so libopencv_ccalib.so.406 libopencv_core.so
libopencv_core.so.406 libopencv_cvv.so libopencv_cvv.so.406
libopencv_datasets.so libopencv_datasets.so.406 libopencv_dnn.so
libopencv_dnn.so.406 libopencv_dnn_objdetect.so
libopencv_dnn_objdetect.so.406 libopencv_dnn_superres.so
libopencv_dnn_superres.so.406 libopencv_dpm.so libopencv_dpm.so.406
libopencv_face.so libopencv_face.so.406 libopencv_features2d.so
libopencv_features2d.so.406 libopencv_flann.so libopencv_flann.so.406
libopencv_freetype.so libopencv_freetype.so.406 libopencv_fuzzy.so
libopencv_fuzzy.so.406 libopencv_hdf.so libopencv_hdf.so.406
libopencv_hfs.so libopencv_hfs.so.406 libopencv_highgui.so
libopencv_highgui.so.406 libopencv_img_hash.so libopencv_img_hash.so.406
libopencv_imgcodecs.so libopencv_imgcodecs.so.406 libopencv_imgproc.so
libopencv_imgproc.so.406 libopencv_intensity_transform.so
libopencv_intensity_transform.so.406 libopencv_line_descriptor.so
libopencv_line_descriptor.so.406 libopencv_mcc.so libopencv_mcc.so.406
libopencv_ml.so libopencv_ml.so.406 libopencv_objdetect.so
libopencv_objdetect.so.406 libopencv_optflow.so libopencv_optflow.so.406
libopencv_phase_unwrapping.so libopencv_phase_unwrapping.so.406
libopencv_photo.so libopencv_photo.so.406 libopencv_plot.so
libopencv_plot.so.406 libopencv_quality.so libopencv_quality.so.406
libopencv_rapid.so libopencv_rapid.so.406 libopencv_reg.so
libopencv_reg.so.406 libopencv_rgbd.so libopencv_rgbd.so.406
libopencv_saliency.so libopencv_saliency.so.406 libopencv_shape.so
libopencv_shape.so.406 libopencv_stereo.so libopencv_stereo.so.406
libopencv_stitching.so libopencv_stitching.so.406
libopencv_structured_light.so libopencv_structured_light.so.406
libopencv_superres.so libopencv_superres.so.406
libopencv_surface_matching.so libopencv_surface_matching.so.406
libopencv_text.so libopencv_text.so.406 libopencv_tracking.so
libopencv_tracking.so.406 libopencv_video.so libopencv_video.so.406
libopencv_videoio.so libopencv_videoio.so.406 libopencv_videostab.so
libopencv_videostab.so.406 libopencv_viz.so libopencv_viz.so.406
libopencv_wechat_qrcode.so libopencv_wechat_qrcode.so.406
libopencv_ximgproc.so libopencv_ximgproc.so.406 libopencv_xobjdetect.so
libopencv_xobjdetect.so.406 libopencv_xphoto.so libopencv_xphoto.so.406
libopenjp2.so libopenjp2.so.7 libopenmpt.so.0 libopus.so.0 liborc-0.4.so
liborc-0.4.so.0 liborc-test-0.4.so liborc-test-0.4.so.0 liboshmem.so.40
libp11-kit.so libpanel.so.6 libpango-1.0.so libpango-1.0.so.0
libpangocairo-1.0.so libpangocairo-1.0.so.0 libpangoft2-1.0.so
libpangoft2-1.0.so.0 libpangomm-2.48.so libpangomm-2.48.so.1
libpangoxft-1.0.so libpangoxft-1.0.so.0 libpathplan.so libpathplan.so.4
libpciaccess.so libpcre.so libpcre.so.3 libpcre16.so libpcre16.so.3
libpcre2-16.so libpcre2-16.so.0 libpcre2-32.so libpcre2-32.so.0
libpcre2-8.so libpcre2-posix.so libpcre2-posix.so.3 libpcre32.so
libpcre32.so.3 libpcrecpp.so libpcrecpp.so.0 libpcreposix.so
libpcreposix.so.3 libpeas-1.0.so libpeas-1.0.so.0 libpeas-gtk-1.0.so
libpeas-gtk-1.0.so.0 libpgm-5.3.so.0 libpipewire-0.3.so.0 libpipewire-
module-access.so libpipewire-module-adapter.so libpipewire-module-avb.so
libpipewire-module-client-device.so libpipewire-module-client-node.so
libpipewire-module-combine-stream.so libpipewire-module-echo-cancel.so
libpipewire-module-fallback-sink.so libpipewire-module-filter-chain.so
libpipewire-module-jack-tunnel.so libpipewire-module-jackdbus-detect.so
libpipewire-module-link-factory.so libpipewire-module-loopback.so
libpipewire-module-metadata.so libpipewire-module-netjack2-driver.so
libpipewire-module-netjack2-manager.so libpipewire-module-pipe-tunnel.so
libpipewire-module-portal.so libpipewire-module-profiler.so libpipewire-
module-protocol-native.so libpipewire-module-protocol-pulse.so
libpipewire-module-protocol-simple.so libpipewire-module-pulse-tunnel.so
libpipewire-module-raop-discover.so libpipewire-module-raop-sink.so
libpipewire-module-roc-sink.so libpipewire-module-roc-source.so
libpipewire-module-rt.so libpipewire-module-rtkit.so libpipewire-module-
rtp-sap.so libpipewire-module-rtp-session.so libpipewire-module-rtp-
sink.so libpipewire-module-rtp-source.so libpipewire-module-session-
manager.so libpipewire-module-spa-device-factory.so libpipewire-module-
spa-device.so libpipewire-module-spa-node-factory.so libpipewire-module-
spa-node.so libpipewire-module-vban-recv.so libpipewire-module-vban-
send.so libpipewire-module-zeroconf-discover.so libpixbufloader-ani.so
libpixbufloader-bmp.so libpixbufloader-gif.so libpixbufloader-heif.so
libpixbufloader-icns.so libpixbufloader-ico.so libpixbufloader-pnm.so
libpixbufloader-qtif.so libpixbufloader-tga.so libpixbufloader-tiff.so
libpixbufloader-webp.so libpixbufloader-xbm.so libpixbufloader-xpm.so
libpixbufloader_svg.so libpixman-1.so libpixman-1.so.0 libpkgconf.so.3
libplc4.so libplds4.so libpmix.so.2 libpng.so libpng16.so libpoppler-
glib.so libpoppler-glib.so.8 libpoppler.so libpoppler.so.134 libportal-
gtk3.so libportal-gtk3.so.1 libportal-gtk4.so libportal-gtk4.so.1
libportal.so libportal.so.1 libpq.so.5 libpresage.so.1 libprintbackend-
cups.so libprintbackend-file.so libprintbackend-lpr.so libprintbackend-
test.so libproj.so.25 libprotobuf.so.32 libproxy.so.1 libpsl.so
libpsl.so.5 libpsm2.so.2 libpspell.so.15 libpulse-mainloop-glib.so
libpulse-mainloop-glib.so.0 libpulse-simple.so libpulse-simple.so.0
libpulse.so libpulse.so.0 libpulsecommon-16.1.so libpxbackend-1.0.so
libpython3.12.so libpython3.12.so.1 libpython3loader.so
libqconnmanbearer.so libqedr-rdmav34.so libqeglfs-emu-integration.so
libqeglfs-kms-egldevice-integration.so libqeglfs-kms-integration.so
libqeglfs-x11-integration.so libqeglfs.so libqevdevkeyboardplugin.so
libqevdevmouseplugin.so libqevdevtabletplugin.so libqevdevtouchplugin.so
libqgenericbearer.so libqgif.so libqico.so libqjpeg.so
libqlibinputplugin.so libqlinuxfb.so libqminimal.so libqminimalegl.so
libqnmbearer.so libqoffscreen.so libqtuiotouchplugin.so libquadmath.so
libquadmath.so.0 libqvnc.so libqxcb-egl-integration.so libqxcb-glx-
integration.so libqxcb.so librabbitmq.so.4 librav1e.so.0 libraw1394.so
libraw1394.so.11 librdmacm.so.1 libremote.so libresolv.so librest-1.0.so
librest-1.0.so.0 librest-extras-1.0.so librest-extras-1.0.so.0
librist.so.4 libroc.so.0 librom1394.so.0 librpf.so librspreload.so
librspreload.so.1 librsvg-2.so librsvg-2.so.2 librtmp.so.1 librttopo.so.1
librxe-rdmav34.so libsasl2.so.2 libsasldb.so libsasldb.so.2 libseccomp.so
libsecondtime.so libsecret-1.so libsecret-1.so.0 libselinux.so libsepol.so
libsframe.so.1 libsharpyuv.so libsharpyuv.so.0 libshine.so.3 libshout.so.3
libsigc-2.0.so libsigc-2.0.so.0 libsigc-3.0.so libsigc-3.0.so.0 libsiw-
rdmav34.so libskeleton.so libslang.so.2 libsmime3.so libsnapd-glib-2.so.1
libsnappy.so.1 libsndfile.so.1 libsocket++.so.1 libsodium.so.23
libsoftokn3.so libsoup-3.0.so libsoup-3.0.so.0 libsoxr.so.0 libspa-aec-
null.so libspa-aec-webrtc.so libspa-alsa.so libspa-audioconvert.so libspa-
audiomixer.so libspa-audiotestsrc.so libspa-avb.so libspa-control.so
libspa-dbus.so libspa-journal.so libspa-support.so libspa-test.so
libspa-v4l2.so libspa-videoconvert.so libspa-videotestsrc.so
libspatialite.so.8 libspeex.so.1 libspeexdsp.so.1 libsqlite3.so libssh-
gcrypt.so.4 libssh.so.4 libssh2.so.1 libssl3.so libstdc++.so
libsuperlu.so.6 libswresample.so libswresample.so.4 libswscale.so
libswscale.so.7 libsystemd.so libsz.so.2 libtag.so.1 libtasn1.so libtbb.so
libtbb.so.12 libtbbbind_2_5.so libtbbbind_2_5.so.3 libtbbmalloc.so
libtbbmalloc.so.2 libtbbmalloc_proxy.so libtbbmalloc_proxy.so.2
libtcl8.6.so libtcl8.6.so.0 libtdb.so libtdb.so.1 libtesseract.so.5
libthai.so libthai.so.0 libtheora.so.0 libtheoradec.so.1 libtheoraenc.so.1
libthread_db.so libtiff.so libtiff.so.6 libtiffxx.so libtiffxx.so.6
libtirpc.so libtk8.6.so libtk8.6.so.0 libtsan.so libtsan.so.2
libtwolame.so.0 libubsan.so libubsan.so.1 libucm.so.0 libucp.so.0
libucs.so.0 libucs_signal.so.0 libuct.so.0 libuct_cma.so.0 libuct_ib.so.0
libuct_rdmacm.so.0 libucx_perftest_rocm.so.0 libudev.so libudfread.so.0
libunbound.so.8 libunity-extras.so libunity-extras.so.9 libunity-gtk-
module.so libunity-gtk3-parser.so.0 libunity-protocol-private.so libunity-
protocol-private.so.0 libunity.so libunity.so.9 libunwind-coredump.so
libunwind-coredump.so.0 libunwind-generic.so libunwind-ptrace.so
libunwind-ptrace.so.0 libunwind-x86_64.so libunwind-x86_64.so.8
libunwind.so libunwind.so.8 liburiparser.so.1 libusb-1.0.so.0 libuuid.so
libuv.so.1 libv4l-mplane.so libv4l1.so.0 libv4l2.so.0 libv4lconvert.so.0
libva-glx.so libva-glx.so.2 libvisual-0.4.so.0 libvmw_pvrdma-rdmav34.so
libvorbis.so.0 libvorbisenc.so.2 libvorbisfile.so.3 libvpf.so.4
libvpl.so.2 libvpl_wayland.so libvpx.so.9 libvrf.so libvte-2.91.so.0
libvtkChartsCore-9.1.so.1 libvtkCommonColor-9.1.so.1
libvtkCommonComputationalGeometry-9.1.so.1 libvtkCommonCore-9.1.so.1
libvtkCommonDataModel-9.1.so.1 libvtkCommonExecutionModel-9.1.so.1
libvtkCommonMath-9.1.so.1 libvtkCommonMisc-9.1.so.1
libvtkCommonPython-9.1.so.1 libvtkCommonSystem-9.1.so.1
libvtkCommonTransforms-9.1.so.1 libvtkDICOMParser-9.1.so.1
libvtkDomainsChemistry-9.1.so.1 libvtkDomainsChemistryOpenGL2-9.1.so.1
libvtkDomainsParallelChemistry-9.1.so.1 libvtkFiltersAMR-9.1.so.1
libvtkFiltersCore-9.1.so.1 libvtkFiltersExtraction-9.1.so.1
libvtkFiltersFlowPaths-9.1.so.1 libvtkFiltersGeneral-9.1.so.1
libvtkFiltersGeneric-9.1.so.1 libvtkFiltersGeometry-9.1.so.1
libvtkFiltersHybrid-9.1.so.1 libvtkFiltersHyperTree-9.1.so.1
libvtkFiltersImaging-9.1.so.1 libvtkFiltersModeling-9.1.so.1
libvtkFiltersParallel-9.1.so.1 libvtkFiltersParallelGeometry-9.1.so.1
libvtkFiltersParallelImaging-9.1.so.1 libvtkFiltersParallelMPI-9.1.so.1
libvtkFiltersParallelVerdict-9.1.so.1 libvtkFiltersPoints-9.1.so.1
libvtkFiltersProgrammable-9.1.so.1 libvtkFiltersPython-9.1.so.1
libvtkFiltersSMP-9.1.so.1 libvtkFiltersSelection-9.1.so.1
libvtkFiltersSources-9.1.so.1 libvtkFiltersStatistics-9.1.so.1
libvtkFiltersTexture-9.1.so.1 libvtkFiltersTopology-9.1.so.1
libvtkFiltersVerdict-9.1.so.1 libvtkGeovisCore-9.1.so.1
libvtkIOAMR-9.1.so.1 libvtkIOAsynchronous-9.1.so.1
libvtkIOCGNSReader-9.1.so.1 libvtkIOCONVERGECFD-9.1.so.1
libvtkIOChemistry-9.1.so.1 libvtkIOCityGML-9.1.so.1 libvtkIOCore-9.1.so.1
libvtkIOEnSight-9.1.so.1 libvtkIOExodus-9.1.so.1 libvtkIOExport-9.1.so.1
libvtkIOExportGL2PS-9.1.so.1 libvtkIOExportPDF-9.1.so.1
libvtkIOGeometry-9.1.so.1 libvtkIOHDF-9.1.so.1 libvtkIOIOSS-9.1.so.1
libvtkIOImage-9.1.so.1 libvtkIOImport-9.1.so.1 libvtkIOInfovis-9.1.so.1
libvtkIOLSDyna-9.1.so.1 libvtkIOLegacy-9.1.so.1 libvtkIOMINC-9.1.so.1
libvtkIOMPIImage-9.1.so.1 libvtkIOMPIParallel-9.1.so.1
libvtkIOMotionFX-9.1.so.1 libvtkIOMovie-9.1.so.1 libvtkIONetCDF-9.1.so.1
libvtkIOOggTheora-9.1.so.1 libvtkIOPLY-9.1.so.1 libvtkIOParallel-9.1.so.1
libvtkIOParallelNetCDF-9.1.so.1 libvtkIOParallelXML-9.1.so.1
libvtkIOSQL-9.1.so.1 libvtkIOSegY-9.1.so.1 libvtkIOTecplotTable-9.1.so.1
libvtkIOVeraOut-9.1.so.1 libvtkIOVideo-9.1.so.1 libvtkIOXML-9.1.so.1
libvtkIOXMLParser-9.1.so.1 libvtkImagingColor-9.1.so.1
libvtkImagingCore-9.1.so.1 libvtkImagingFourier-9.1.so.1
libvtkImagingGeneral-9.1.so.1 libvtkImagingHybrid-9.1.so.1
libvtkImagingMath-9.1.so.1 libvtkImagingMorphological-9.1.so.1
libvtkImagingSources-9.1.so.1 libvtkImagingStatistics-9.1.so.1
libvtkImagingStencil-9.1.so.1 libvtkInfovisCore-9.1.so.1
libvtkInfovisLayout-9.1.so.1 libvtkInteractionImage-9.1.so.1
libvtkInteractionStyle-9.1.so.1 libvtkInteractionWidgets-9.1.so.1
libvtkJava-9.1.so.1 libvtkParallelCore-9.1.so.1 libvtkParallelDIY-9.1.so.1
libvtkParallelMPI-9.1.so.1 libvtkParallelMPI4Py-9.1.so.1
libvtkPythonContext2D-9.1.so.1 libvtkPythonInterpreter-9.1.so.1
libvtkRenderingAnnotation-9.1.so.1 libvtkRenderingContext2D-9.1.so.1
libvtkRenderingContextOpenGL2-9.1.so.1 libvtkRenderingCore-9.1.so.1
libvtkRenderingFreeType-9.1.so.1 libvtkRenderingGL2PSOpenGL2-9.1.so.1
libvtkRenderingImage-9.1.so.1 libvtkRenderingLOD-9.1.so.1
libvtkRenderingLabel-9.1.so.1 libvtkRenderingOpenGL2-9.1.so.1
libvtkRenderingSceneGraph-9.1.so.1 libvtkRenderingTk-9.1.so.1
libvtkRenderingUI-9.1.so.1 libvtkRenderingVolume-9.1.so.1
libvtkRenderingVolumeOpenGL2-9.1.so.1 libvtkRenderingVtkJS-9.1.so.1
libvtkTestingRendering-9.1.so.1 libvtkViewsContext2D-9.1.so.1
libvtkViewsCore-9.1.so.1 libvtkViewsInfovis-9.1.so.1
libvtkWrappingPythonCore3.12-9.1.so.1 libvtkWrappingTools-9.1.so.1
libvtkcgns-9.1.so.1 libvtkexodusII-9.1.so.1 libvtkfmt-9.1.so.1
libvtkioss-9.1.so.1 libvtkkissfft-9.1.so.1 libvtklibharu-9.1.so.1
libvtkloguru-9.1.so.1 libvtkmetaio-9.1.so.1 libvtkpugixml-9.1.so.1
libvtksys-9.1.so.1 libvtkverdict-9.1.so.1 libwacom.so libwacom.so.9
libwavpack.so.1 libwebkit2gtk-4.1.so libwebkit2gtk-4.1.so.0
libwebkit2gtkinjectedbundle.so libwebp.so libwebp.so.7 libwebpdecoder.so
libwebpdecoder.so.3 libwebpdemux.so libwebpdemux.so.2 libwebpmux.so
libwebpmux.so.3 libwebrtc_audio_processing.so.1 libwrap.so
libx11_plugin.so libx11_plugin.so.0 libx264.so.164 libx265.so
libx265.so.199 libxcb-icccm.so.4 libxcb-image.so.0 libxcb-keysyms.so.1
libxcb-render-util.so.0 libxcb-render.so libxcb-render.so.0 libxcb-
shape.so.0 libxcb-util.so.1 libxcb-xinerama.so.0 libxcb-xinput.so.0
libxcb-xkb.so.1 libxdot.so libxdot.so.4 libxerces-c-3.2.so
libxkbcommon-x11.so.0 libxkbcommon.so libxml2mod.cpython-312-x86_64-linux-
gnu.so libxmlb.so.2 libxslt.so.1 libxvidcore.so.4 libyaml.so libz.so
libzmq.so.5 libzstd.so libzvbi-chains.so.0 libzvbi.so.0
""".split())

# noble renamed these for 64-bit time_t: libasound2 is libasound2t64.
RENAMED_T64 = frozenset("""
libarchive13 libasound2 libatk-bridge2.0-0 libatk1.0-0 libatopology2
libatspi2.0-0 libbasicobjects0 libcamel-1.2-64 libcdio-cdda2 libcdio-
paranoia2 libcdio19 libcollection4 libcolord-gtk4-1 libcups2
libcupsfilters2 libcupsimage2 libcurl4 libdb5.3 libdebuginfod1 libdhash1
libdv4 libdvdread8 libdw1 libebackend-1.2-11 libebook-1.2-21 libebook-
contacts-1.2-4 libedata-book-1.2-27 libedata-cal-2.0-2
libedataserver-1.2-27 libedataserverui-1.2-4 libefiboot1 libefivar1
libelf1 libevent-core-2.1-7 libext2fs2 libgdbm-compat4 libgdbm6
libglib2.0-0 libgnome-bg-4-2 libgnome-desktop-3-20 libgnome-desktop-4-2
libgnutls30 libgphoto2-6 libgphoto2-port12 libgsound0 libgtk-3-0
libgweather-4-0 libgxps2 libhogweed6 libhwy1 libical3 libieee1284-3
libini-config5 libipa-hbac0 liblouisutdml9 libmagic1 libmpg123-0
libmspack0 libmtdev1 libmtp9 libnettle8 libnorm1 libnpth0 libntfs-3g89
libnvme1 libonnx1 libopenmpt0 liborc-0.4-0 libparted2 libpath-utils1
libpcap0.8 libpgm-5.3-0 libpipewire-0.3-0 libpkcs11-helper1 libpng16-16
libpoppler-glib8 libprotobuf32 libpsl5 libreadline8 libref-array1
libsnmp40 libsource-highlight4 libssh2-1 libssl3 libtevent0 libtirpc3
libtss2-esys-3.0.2-0 libtss2-mu-4.0.1-0 libtss2-rc0 libtss2-sys1
libtss2-tcti-cmd0 libtss2-tcti-device0 libtss2-tcti-mssim0 libtss2-tcti-
swtpm0 liburcu8 libuv1 libv4l-0 libv4lconvert0 libxt6 libzvbi0
""".split())

# Packages the base already covers, whatever a Depends: says.
SUPPLIED_BY_BASE = frozenset("""
iptables libacl1 libapparmor1 libattr1 libaudit1 libblkid1 libbpf1
libbrotli1 libbsd0 libbz2-1.0 libc-gconv-modules-extra libc6 libcap-ng0
libcap2 libcom-err2 libcrack2 libcrypt1 libcryptsetup12 libdb5.3
libdb5.3t64 libdbus-1-3 libdebconfclient0 libdrm2 libduktape207 libedit2
libevdev2 libexpat1 libext2fs2 libext2fs2t64 libfdisk1 libffi8 libfido2-1
libfreetype6 libgcc-s1 libgcrypt20 libglib2.0-0 libglib2.0-0t64 libgmp10
libgnutls30 libgnutls30t64 libgpg-error0 libgssapi-krb5-2 libhogweed6
libhogweed6t64 libidn2-0 libip4tc2 libip6tc2 libjson-c5 libk5crypto3
libkeyutils1 libkmod2 libkrb5-3 libkrb5support0 liblz4-1 liblzma5
liblzo2-2 libmagic1 libmagic1t64 libmd0 libmnl0 libmount1 libncursesw6
libnetfilter-conntrack3 libnetplan1 libnettle8 libnettle8t64 libnfnetlink0
libnftnl11 libnl-3-200 libnl-genl-3-200 libnl-route-3-200 libnpth0
libnpth0t64 libp11-kit0 libpam0g libpciaccess0 libpcre2-8-0 libplymouth5
libpng16-16 libpng16-16t64 libpolkit-agent-1-0 libpolkit-gobject-1-0
libpopt0 libproc2-0 libpwquality1 libreadline8 libreadline8t64 libseccomp2
libselinux1 libsemanage2 libsepol2 libsmartcols1 libsqlite3-0 libss2
libssl3 libssl3t64 libstdc++6 libsystemd0 libtasn1-6 libtinfo6 libtirpc3
libtirpc3t64 libudev1 libunistring5 libuuid1 libwrap0 libxkbcommon0
libxtables12 libxxhash0 libyaml-0-2 libzstd1 systemd-cryptsetup zlib1g
""".split())

# And the ones the gnome extension covers, for apps that use it.
SUPPLIED_BY_GNOME = frozenset("""
binutils-x86-64-linux-gnu dconf-gsettings-backend glib-networking
gstreamer1.0-gl gstreamer1.0-pipewire gstreamer1.0-plugins-base heif-gdk-
pixbuf libaa1 libadwaita-1-0 libaom3 libappstream5 libarchive13
libarchive13t64 libasound2 libasound2t64 libaspell15 libasyncns0 libatk-
adaptor libatk-bridge2.0-0 libatk-bridge2.0-0t64 libatk1.0-0
libatk1.0-0t64 libatomic1 libatspi2.0-0 libatspi2.0-0t64 libavahi-client3
libavahi-common3 libavc1394-0 libayatana-ido3-0.4-0 libayatana-
indicator3-7 libc6-dev libcaca0 libcairo-gobject2 libcairo-script-
interpreter2 libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module
libcanberra-pulse libcanberra0 libcdparanoia0 libchromaprint1 libcjson1
libcolord2 libctf-nobfd0 libctf0 libcups2 libcups2t64 libcurl3t64-gnutls
libcurl4 libcurl4t64 libdatrie1 libdav1d7 libdbusmenu-glib4 libdbusmenu-
gtk3-4 libdconf1 libdee-1.0-4 libdeflate0 libdv4 libdv4t64 libenchant-2-2
libepoxy0 libevent-core-2.1-7 libevent-core-2.1-7t64 libexif12
libfontconfig1 libfribidi0 libgck-1-0 libgcr-base-3-1 libgcr-ui-3-1 libgd3
libgdbm-compat4 libgdbm-compat4t64 libgdbm6 libgdbm6t64 libgdk-
pixbuf-2.0-0 libgee-0.8-2 libgeocode-glib-2-0 libgif7
libgirepository-1.0-1 libgirepository-2.0-0 libgjs0 libgme0 libgnome-
bg-4-2 libgnome-bg-4-2t64 libgnome-desktop-3-20 libgnome-desktop-3-20t64
libgnome-desktop-4-2 libgnome-desktop-4-2t64 libgoa-1.0-0b libgomp1
libgphoto2-6 libgphoto2-6t64 libgphoto2-port12 libgphoto2-port12t64
libgpm2 libgprofng0 libgraphene-1.0-0 libgraphite2-3 libgsm1 libgsound0
libgsound0t64 libgssdp-1.6-0 libgstreamer-gl1.0-0 libgstreamer-plugins-
base1.0-0 libgstreamer-plugins-extra1.0-0 libgstreamer1.0-0 libgtk-3-0
libgtk-3-0t64 libgtk-4-1 libgtksourceview-5-0 libgudev-1.0-0
libgupnp-1.6-0 libgweather-4-0 libgweather-4-0t64 libhandy-1-0
libharfbuzz-gobject0 libharfbuzz-icu0 libharfbuzz-subset0 libharfbuzz0b
libheif-plugin-aomdec libheif1 libhunspell-1.7-0 libhwy1 libhwy1t64
libhyphen0 libibus-1.0-5 libibverbs1 libice6 libiec61883-0 libinput10
libisl23 libjansson4 libjavascriptcoregtk-4.1-0 libjbig0 libjpeg-turbo8
libjson-glib-1.0-0 liblcms2-2 libldap2 liblerc4 libltdl7 libmp3lame0
libmpc3 libmpfr6 libmpg123-0 libmpg123-0t64 libmtdev1 libmtdev1t64
libncurses6 libnghttp2-14 libnorm1 libnorm1t64 libnotify4 libnspr4 libnss3
libnuma1 libogg0 libopenjp2-7 libopenmpt0 libopenmpt0t64 libopus0
liborc-0.4-0 liborc-0.4-0t64 libpango-1.0-0 libpangocairo-1.0-0
libpangoft2-1.0-0 libpangoxft-1.0-0 libpcre2-32-0 libpgm-5.3-0
libpgm-5.3-0t64 libpipewire-0.3-0 libpipewire-0.3-0t64 libpixman-1-0
libpoppler-glib8 libpoppler-glib8t64 libportal-gtk4-1 libportal1
libprotobuf32 libprotobuf32t64 libproxy1v5 libpsl5 libpsl5t64 libpulse-
mainloop-glib0 librabbitmq4 libraw1394-11 librest-1.0-0 librist4
librsvg2-2 librsvg2-common librtmp1 libsasl2-2 libsasl2-modules-db
libsecret-1-0 libsharpyuv0 libshine3 libshout3 libslang2 libsm6 libsnapd-
glib-2-1 libsnappy1v5 libsndfile1 libsodium23 libsoup-3.0-0 libsoxr0
libspeex1 libspeexdsp1 libssh-4 libssh2-1 libssh2-1t64 libtcl8.6 libtdb1
libthai0 libtiff6 libtwolame0 libunity-protocol-private0 libunity9
libunwind8 libusb-1.0-0 libuv1 libuv1t64 libv4lconvert0 libv4lconvert0t64
libvisual-0.4-0 libvorbis0a libvorbisenc2 libvorbisfile3 libvpl2
libvte-2.91-0 libwacom9 libwavpack1 libwebkit2gtk-4.1-0 libwebp7
libwebpdemux2 libwebpmux3 libxcb-render0 libxcb-shape0 libxcb-util1
libxcomposite1 libxcursor1 libxft2 libxi6 libxinerama1 libxmlb2
libxnvctrl0 libxpm4 libxrandr2 libxrender1 libxslt1.1 libxt6 libxt6t64
libxtst6 libxvidcore4 libzmq5 libzvbi0 libzvbi0t64 ocl-icd-libopencl1
webp-pixbuf-loader
""".split())

# Driver libraries an interface supplies, never staged.
FROM_THE_HOST = frozenset("""
libEGL_nvidia.so.0 libGLESv2_nvidia.so.2 libGLX_nvidia.so.0 libcuda.so.1
libnvcuvid.so.1 libnvidia-ml.so.1 libnvoptix.so.1 libvulkan_intel.so
libvulkan_radeon.so
""".split())

# Which package ships a soname, where evidence says so, not a guess.
PACKAGE_OF = {
    "libEGL.so.1": "libegl1",
    "libEGL_mesa.so.0": "libegl-mesa0",
    "libFLAC.so.14": "libflac14",
    "libGL.so.1": "libgl1",
    "libGLESv1_CM.so.1": "libgles1",
    "libGLESv2.so.2": "libgles2",
    "libGLU.so.1": "libglu1-mesa",
    "libGLX.so.0": "libglx0",
    "libGLX_mesa.so.0": "libglx-mesa0",
    "libGLdispatch.so.0": "libglvnd0",
    "libICE.so.6": "libice6",
    "libINIReader.so.0": "libinireader0",
    "libLerc.so.4": "liblerc4",
    "libOpenCL.so.1": "ocl-icd-libopencl1",
    "libOpenGL.so.0": "libopengl0",
    "libSM.so.6": "libsm6",
    "libSvtAv1Enc.so.2": "libsvtav1enc2",
    "libX11-xcb.so.1": "libx11-xcb1",
    "libX11.so.6": "libx11-6",
    "libXNVCtrl.so.0": "libxnvctrl0",
    "libXRes.so.1": "libxres1",
    "libXau.so.6": "libxau6",
    "libXaw.so.7": "libxaw7",
    "libXcomposite.so.1": "libxcomposite1",
    "libXcursor.so.1": "libxcursor1",
    "libXdamage.so.1": "libxdamage1",
    "libXdmcp.so.6": "libxdmcp6",
    "libXext.so.6": "libxext6",
    "libXfixes.so.3": "libxfixes3",
    "libXft.so.2": "libxft2",
    "libXi.so.6": "libxi6",
    "libXinerama.so.1": "libxinerama1",
    "libXmu.so.6": "libxmu6",
    "libXmuu.so.1": "libxmuu1",
    "libXpm.so.4": "libxpm4",
    "libXrandr.so.2": "libxrandr2",
    "libXrender.so.1": "libxrender1",
    "libXt.so.6": "libxt6t64",
    "libXtst.so.6": "libxtst6",
    "libXv.so.1": "libxv1",
    "libXxf86dga.so.1": "libxxf86dga1",
    "libXxf86vm.so.1": "libxxf86vm1",
    "libaa.so.1": "libaa1",
    "libaacs.so.0": "libaacs0",
    "libaccountsservice.so.0": "libaccountsservice0",
    "libadwaita-1.so.0": "libadwaita-1-0",
    "libao.so.4": "libao4",
    "libaom.so.3": "libaom3",
    "libappindicator3.so.1": "libappindicator3-1",
    "libappstream.so.5": "libappstream5",
    "libarchive.so.13": "libarchive13t64",
    "libasound.so.2": "libasound2t64",
    "libaspell.so.15": "libaspell15",
    "libass.so.9": "libass9",
    "libassuan.so.9": "libassuan9",
    "libasyncns.so.0": "libasyncns0",
    "libatasmart.so.4": "libatasmart4",
    "libatk-1.0.so.0": "libatk1.0-0t64",
    "libatk-bridge-2.0.so.0": "libatk-bridge2.0-0t64",
    "libatomic.so.1": "libatomic1",
    "libatopology.so.2": "libatopology2t64",
    "libatspi.so.0": "libatspi2.0-0t64",
    "libavahi-client.so.3": "libavahi-client3",
    "libavahi-common.so.3": "libavahi-common3",
    "libavahi-core.so.7": "libavahi-core7",
    "libavahi-glib.so.1": "libavahi-glib1",
    "libavc1394.so.0": "libavc1394-0",
    "libavcodec.so.62": "libavcodec62",
    "libavfilter.so.11": "libavfilter11",
    "libavformat.so.62": "libavformat62",
    "libavutil.so.60": "libavutil60",
    "libayatana-appindicator3.so.1": "libayatana-appindicator3-1",
    "libayatana-ido3-0.4.so.0": "libayatana-ido3-0.4-0",
    "libayatana-indicator3.so.7": "libayatana-indicator3-7",
    "libbabeltrace.so.1": "libbabeltrace1",
    "libbasicobjects.so.0": "libbasicobjects0t64",
    "libbdplus.so.0": "libbdplus0",
    "libblockdev.so.3": "libblockdev3",
    "libbluetooth.so.3": "libbluetooth3",
    "libbluray.so.3": "libbluray3",
    "libbs2b.so.0": "libbs2b0",
    "libbytesize.so.1": "libbytesize1",
    "libcaca++.so.0": "libcaca0",
    "libcaca.so.0": "libcaca0",
    "libcairo-gobject.so.2": "libcairo-gobject2",
    "libcairo-script-interpreter.so.2": "libcairo-script-interpreter2",
    "libcairo.so.2": "libcairo2",
    "libcamel-1.2.so.64": "libcamel-1.2-64t64",
    "libcanberra-gtk3.so.0": "libcanberra-gtk3-0",
    "libcanberra.so.0": "libcanberra0",
    "libcares.so.2": "libcares2",
    "libcdio.so.19": "libcdio19t64",
    "libcdio_cdda.so.2": "libcdio-cdda2t64",
    "libcdio_paranoia.so.2": "libcdio-paranoia2t64",
    "libchewing.so.3": "libchewing3",
    "libchromaprint.so.1": "libchromaprint1",
    "libcjson.so.1": "libcjson1",
    "libclamav.so.12": "libclamav12",
    "libcollection.so.4": "libcollection4t64",
    "libcolord-gtk4.so.1": "libcolord-gtk4-1t64",
    "libcolord.so.2": "libcolord2",
    "libcolorhug.so.2": "libcolorhug2",
    "libcpuinfo.so.0": "libcpuinfo0",
    "libctf-nobfd.so.0": "libctf-nobfd0",
    "libctf.so.0": "libctf0",
    "libcue.so.2": "libcue2",
    "libcups.so.2": "libcups2t64",
    "libcupsfilters.so.2": "libcupsfilters2t64",
    "libcupsimage.so.2": "libcupsimage2t64",
    "libcurl.so.4": "libcurl4t64",
    "libdaemon.so.0": "libdaemon0",
    "libdatrie.so.1": "libdatrie1",
    "libdav1d.so.7": "libdav1d7",
    "libdbusmenu-glib.so.4": "libdbusmenu-glib4",
    "libdbusmenu-gtk3.so.4": "libdbusmenu-gtk3-4",
    "libdconf.so.1": "libdconf1",
    "libdebuginfod.so.1": "libdebuginfod1t64",
    "libdecor-0.so.0": "libdecor-0-0",
    "libdecor-gtk.so": "libdecor-0-plugin-1-gtk",
    "libdee-1.0.so.4": "libdee-1.0-4",
    "libdeflate.so.0": "libdeflate0",
    "libdhash.so.1": "libdhash1t64",
    "libdisplay-info.so.3": "libdisplay-info3",
    "libdjvulibre.so.21": "libdjvulibre21",
    "libdotconf.so.0": "libdotconf0",
    "libdrm_amdgpu.so.1": "libdrm-amdgpu1",
    "libdrm_intel.so.1": "libdrm-intel1",
    "libdv.so.4": "libdv4t64",
    "libdvdnav.so.4": "libdvdnav4",
    "libdvdread.so.8": "libdvdread8t64",
    "libdw.so.1": "libdw1t64",
    "libeatmydata.so.1": "libeatmydata1",
    "libebackend-1.2.so.11": "libebackend-1.2-11t64",
    "libebook-1.2.so.21": "libebook-1.2-21t64",
    "libebook-contacts-1.2.so.4": "libebook-contacts-1.2-4t64",
    "libebur128.so.1": "libebur128-1",
    "libecal-2.0.so.3": "libecal-2.0-3",
    "libedata-book-1.2.so.27": "libedata-book-1.2-27t64",
    "libedata-cal-2.0.so.2": "libedata-cal-2.0-2t64",
    "libedataserver-1.2.so.27": "libedataserver-1.2-27t64",
    "libedataserverui-1.2.so.4": "libedataserverui-1.2-4t64",
    "libefiboot.so.1": "libefiboot1t64",
    "libefivar.so.1": "libefivar1t64",
    "libei.so.1": "libei1",
    "libeis.so.1": "libeis1",
    "libenchant-2.so.2": "libenchant-2-2",
    "libepoxy.so.0": "libepoxy0",
    "libespeak-ng.so.1": "libespeak-ng1",
    "libestr.so.0": "libestr0",
    "libevent_core-2.1.so.7": "libevent-core-2.1-7t64",
    "libexempi.so.8": "libexempi8",
    "libexif.so.12": "libexif12",
    "libexiv2.so.28": "libexiv2-28",
    "libfastjson.so.4": "libfastjson4",
    "libfdk-aac.so.2": "libfdk-aac2",
    "libflashrom.so.1": "libflashrom1",
    "libflite.so.1": "libflite1",
    "libfontconfig.so.1": "libfontconfig1",
    "libfontenc.so.1": "libfontenc1",
    "libfprint-2-tod.so.1": "libfprint-2-tod1",
    "libfprint-2.so.2": "libfprint-2-2",
    "libfreeaptx.so.0": "libfreeaptx0",
    "libfreebl3.so": "libnss3",
    "libfreeblpriv3.so": "libnss3",
    "libfribidi.so.0": "libfribidi0",
    "libftdi1.so.2": "libftdi1-2",
    "libfuse3.so.4": "libfuse3-4",
    "libfwupd.so.3": "libfwupd3",
    "libfyaml.so.0": "libfyaml0",
    "libgamemode.so.0": "libgamemode0",
    "libgamemodeauto.so.0": "libgamemodeauto0",
    "libgbm.so.1": "libgbm1",
    "libgck-1.so.0": "libgck-1-0",
    "libgck-2.so.2": "libgck-2-2",
    "libgcr-4.so.4": "libgcr-4-4",
    "libgcr-base-3.so.1": "libgcr-base-3-1",
    "libgcr-ui-3.so.1": "libgcr-ui-3-1",
    "libgd.so.3": "libgd3",
    "libgdbm.so.6": "libgdbm6t64",
    "libgdbm_compat.so.4": "libgdbm-compat4t64",
    "libgdk-3.so.0": "libgtk-3-0t64",
    "libgdk_pixbuf-2.0.so.0": "libgdk-pixbuf-2.0-0",
    "libgdm.so.1": "libgdm1",
    "libgee-0.8.so.2": "libgee-0.8-2",
    "libgeoclue-2.so.0": "libgeoclue-2-0",
    "libgeocode-glib-2.so.0": "libgeocode-glib-2-0",
    "libgexiv2.so.2": "libgexiv2-2",
    "libgif.so.7": "libgif7",
    "libgirepository-1.0.so.1": "libgirepository-1.0-1",
    "libgirepository-2.0.so.0": "libgirepository-2.0-0",
    "libgjs.so.0": "libgjs0",
    "libgl_plugin.so": "libcaca0",
    "libgl_plugin.so.0": "libcaca0",
    "libglycin-2.so.0": "libglycin-2-0",
    "libglycin-gtk4-2.so.0": "libglycin-gtk4-2-0",
    "libgme.so.0": "libgme0",
    "libgnome-autoar-0.so.0": "libgnome-autoar-0-0",
    "libgnome-bg-4.so.2": "libgnome-bg-4-2t64",
    "libgnome-bluetooth-3.0.so.13": "libgnome-bluetooth-3.0-13",
    "libgnome-bluetooth-ui-3.0.so.13": "libgnome-bluetooth-ui-3.0-13",
    "libgnome-desktop-3.so.20": "libgnome-desktop-3-20t64",
    "libgnome-desktop-4.so.2": "libgnome-desktop-4-2t64",
    "libgnome-menu-3.so.0": "libgnome-menu-3-0",
    "libgnome-qr-4.so.0": "libgnome-qr-4-0",
    "libgnome-qr-gtk-4.so.0": "libgnome-qr-gtk-4-0",
    "libgoa-backend-1.0.so.2": "libgoa-backend-1.0-2",
    "libgomp.so.1": "libgomp1",
    "libgpgme.so.45": "libgpgme45",
    "libgpgmepp.so.7": "libgpgmepp7",
    "libgphoto2.so.6": "libgphoto2-6t64",
    "libgphoto2_port.so.12": "libgphoto2-port12t64",
    "libgpm.so.2": "libgpm2",
    "libgprofng.so.0": "libgprofng0",
    "libgraphene-1.0.so.0": "libgraphene-1.0-0",
    "libgraphite2.so.3": "libgraphite2-3",
    "libgs.so.10": "libgs10",
    "libgsf-1.so.114": "libgsf-1-114",
    "libgsm.so.1": "libgsm1",
    "libgsound.so.0": "libgsound0t64",
    "libgssdp-1.6.so.0": "libgssdp-1.6-0",
    "libgtk-3.so.0": "libgtk-3-0t64",
    "libgtk-4.so.1": "libgtk-4-1",
    "libgtksourceview-5.so.0": "libgtksourceview-5-0",
    "libgtop-2.0.so.11": "libgtop-2.0-11",
    "libgudev-1.0.so.0": "libgudev-1.0-0",
    "libgupnp-1.6.so.0": "libgupnp-1.6-0",
    "libgupnp-av-1.0.so.3": "libgupnp-av-1.0-3",
    "libgupnp-dlna-2.0.so.4": "libgupnp-dlna-2.0-4",
    "libgweather-4.so.0": "libgweather-4-0t64",
    "libgxps.so.2": "libgxps2t64",
    "libhandy-1.so.0": "libhandy-1-0",
    "libharfbuzz-gobject.so.0": "libharfbuzz-gobject0",
    "libharfbuzz-icu.so.0": "libharfbuzz-icu0",
    "libharfbuzz-subset.so.0": "libharfbuzz-subset0",
    "libharfbuzz.so.0": "libharfbuzz0b",
    "libheif.so.1": "libheif1",
    "libhpmud.so.0": "libhpmud0",
    "libhunspell-1.7.so.0": "libhunspell-1.7-0",
    "libhwy.so.1": "libhwy1t64",
    "libhyphen.so.0": "libhyphen0",
    "libibus-1.0.so.5": "libibus-1.0-5",
    "libibverbs.so.1": "libibverbs1",
    "libical.so.3": "libical3t64",
    "libidn.so.12": "libidn12",
    "libiec61883.so.0": "libiec61883-0",
    "libieee1284.so.3": "libieee1284-3t64",
    "libimagequant.so.0": "libimagequant0",
    "libimobiledevice-1.0.so.6": "libimobiledevice-1.0-6",
    "libimobiledevice-glue-1.0.so.0": "libimobiledevice-glue-1.0-0",
    "libindicator3.so.7": "libindicator3-7",
    "libini_config.so.5": "libini-config5t64",
    "libinih.so.1": "libinih1",
    "libinput.so.10": "libinput10",
    "libinsights.so.0": "libinsights0",
    "libipa_hbac.so.0": "libipa-hbac0t64",
    "libipt.so.2": "libipt2",
    "libisl.so.23": "libisl23",
    "libjansson.so.4": "libjansson4",
    "libjavascriptcoregtk-4.1.so.0": "libjavascriptcoregtk-4.1-0",
    "libjavascriptcoregtk-6.0.so.1": "libjavascriptcoregtk-6.0-1",
    "libjbig.so.0": "libjbig0",
    "libjbig2dec.so.0": "libjbig2dec0",
    "libjcat.so.1": "libjcat1",
    "libjemalloc.so.2": "libjemalloc2",
    "libjq.so.1": "libjq1",
    "libjson-glib-1.0.so.0": "libjson-glib-1.0-0",
    "libksba.so.8": "libksba8",
    "liblc3.so.1": "liblc3-1",
    "liblcms2.so.2": "liblcms2-2",
    "libldacBT_abr.so.2": "libldacbt-abr2",
    "libldacBT_enc.so.2": "libldacbt-enc2",
    "libldap.so.2": "libldap2",
    "libldb.so.2": "libldb2",
    "liblilv-0.so.0": "liblilv-0-0",
    "liblmdb.so.0": "liblmdb0",
    "liblouis.so.20": "liblouis20",
    "liblouisutdml.so.9": "liblouisutdml9t64",
    "liblsof.so.0": "liblsof0",
    "libltdl.so.7": "libltdl7",
    "liblua5.4.so.0": "liblua5.4-0",
    "libm17n.so.0": "libm17n-0",
    "libmalcontent-0.so.0": "libmalcontent-0-0",
    "libmarisa.so.1": "libmarisa1",
    "libmaxminddb.so.0": "libmaxminddb0",
    "libmbedcrypto.so.16": "libmbedcrypto16",
    "libmbim-glib.so.4": "libmbim-glib4",
    "libmediaart-2.0.so.0": "libmediaart-2.0-0",
    "libmm-glib.so.0": "libmm-glib0",
    "libmozjs-140.so.0": "libmozjs-140-0",
    "libmp3lame.so.0": "libmp3lame0",
    "libmpc.so.3": "libmpc3",
    "libmpfr.so.6": "libmpfr6",
    "libmpg123.so.0": "libmpg123-0t64",
    "libmsgraph-1.so.1": "libmsgraph-1-1",
    "libmspack.so.0": "libmspack0t64",
    "libmtdev.so.1": "libmtdev1t64",
    "libmtp.so.9": "libmtp9t64",
    "libmutter-18.so.0": "libmutter-18-0",
    "libmysofa.so.1": "libmysofa1",
    "libnautilus-extension.so.4": "libnautilus-extension4",
    "libncurses.so.6": "libncurses6",
    "libndp.so.0": "libndp0",
    "libnfs.so.14": "libnfs14",
    "libnfsidmap.so.1": "libnfsidmap1",
    "libnftables.so.1": "libnftables1",
    "libnghttp2.so.14": "libnghttp2-14",
    "libnm.so.0": "libnm0",
    "libnma-gtk4.so.0": "libnma-gtk4-0",
    "libnma.so.0": "libnma0",
    "libnorm.so.1": "libnorm1t64",
    "libnotify.so.4": "libnotify4",
    "libnspr4.so": "libnspr4",
    "libnss3.so": "libnss3",
    "libnssckbi.so": "libnss3",
    "libnssdbm3.so": "libnss3",
    "libnssutil3.so": "libnss3",
    "libntfs-3g.so.89": "libntfs-3g89t64",
    "libnuma.so.1": "libnuma1",
    "libnvidia-egl-wayland.so.1": "libnvidia-egl-wayland1",
    "libnvme.so.1": "libnvme1t64",
    "liboeffis.so.1": "liboeffis1",
    "libogg.so.0": "libogg0",
    "libonig.so.5": "libonig5",
    "libonnx.so.1": "libonnx1t64",
    "libopenjp2.so.7": "libopenjp2-7",
    "libopenmpt.so.0": "libopenmpt0t64",
    "libopus.so.0": "libopus0",
    "liborc-0.4.so.0": "liborc-0.4-0t64",
    "libosinfo-1.0.so.0": "libosinfo-1.0-0",
    "libotf.so.1": "libotf1",
    "libpackagekit-glib2.so.18": "libpackagekit-glib2-18",
    "libpango-1.0.so.0": "libpango-1.0-0",
    "libpangocairo-1.0.so.0": "libpangocairo-1.0-0",
    "libpangoft2-1.0.so.0": "libpangoft2-1.0-0",
    "libpangoxft-1.0.so.0": "libpangoxft-1.0-0",
    "libpaper.so.2": "libpaper2",
    "libparted.so.2": "libparted2t64",
    "libpath_utils.so.1": "libpath-utils1t64",
    "libpcaudio.so.0": "libpcaudio0",
    "libpci.so.3": "libpci3",
    "libpcre2-32.so.0": "libpcre2-32-0",
    "libpgm-5.3.so.0": "libpgm-5.3-0t64",
    "libphonenumber.so.8": "libphonenumber8",
    "libpinyin.so.15": "libpinyin15",
    "libpipeline.so.1": "libpipeline1",
    "libpipewire-0.3.so.0": "libpipewire-0.3-0t64",
    "libpixman-1.so.0": "libpixman-1-0",
    "libpkcs11-helper.so.1": "libpkcs11-helper1t64",
    "libpkgconf.so.7": "libpkgconf7",
    "libplacebo.so.360": "libplacebo360",
    "libplc4.so": "libnspr4",
    "libplds4.so": "libnspr4",
    "libplist-2.0.so.4": "libplist-2.0-4",
    "libpoppler-cpp.so.3": "libpoppler-cpp3",
    "libpoppler-glib.so.8": "libpoppler-glib8t64",
    "libpoppler.so.156": "libpoppler156",
    "libportal-gtk4.so.1": "libportal-gtk4-1",
    "libportal.so.1": "libportal1",
    "libppd.so.2": "libppd2",
    "libppsdocument-4.0.so.6": "libppsdocument-4.0-6",
    "libppsview-4.0.so.5": "libppsview-4.0-5",
    "libprintbackend-cups.so": "libgtk-3-0t64",
    "libprintbackend-file.so": "libgtk-3-0t64",
    "libprotobuf.so.32": "libprotobuf32t64",
    "libpsl.so.5": "libpsl5t64",
    "libpthreadpool.so.0": "libpthreadpool0",
    "libpulse-mainloop-glib.so.0": "libpulse-mainloop-glib0",
    "libpulse-simple.so.0": "libpulse0",
    "libpulse.so.0": "libpulse0",
    "libpulsecommon-17.0.so": "libpulse0",
    "libqmi-glib.so.5": "libqmi-glib5",
    "libqpdf.so.30": "libqpdf30",
    "libqrtr-glib.so.0": "libqrtr-glib0",
    "librabbitmq.so.4": "librabbitmq4",
    "libraqm.so.0": "libraqm0",
    "libraw1394.so.11": "libraw1394-11",
    "libre2.so.11": "libre2-11",
    "libref_array.so.1": "libref-array1t64",
    "librest-1.0.so.0": "librest-1.0-0",
    "librist.so.4": "librist4",
    "librtmp.so.1": "librtmp1",
    "librubberband.so.3": "librubberband3",
    "librygel-core-2.8.so.0": "librygel-core-2.8-0",
    "librygel-db-2.8.so.0": "librygel-db-2.8-0",
    "librygel-renderer-2.8.so.0": "librygel-renderer-2.8-0",
    "librygel-server-2.8.so.0": "librygel-server-2.8-0",
    "libsamplerate.so.0": "libsamplerate0",
    "libsane.so.1": "libsane1",
    "libsasl2.so.2": "libsasl2-2",
    "libsbc.so.1": "libsbc1",
    "libsecret-1.so.0": "libsecret-1-0",
    "libsensors.so.5": "libsensors5",
    "libserd-0.so.0": "libserd-0-0",
    "libsframe.so.3": "libsframe3",
    "libsharpyuv.so.0": "libsharpyuv0",
    "libshine.so.3": "libshine3",
    "libshout.so.3": "libshout3",
    "libsimdutf.so.31": "libsimdutf31",
    "libslang.so.2": "libslang2",
    "libsmbclient.so.0": "libsmbclient0",
    "libsmime3.so": "libnss3",
    "libsnapd-glib-2.so.1": "libsnapd-glib-2-1",
    "libsnappy.so.1": "libsnappy1v5",
    "libsndfile.so.1": "libsndfile1",
    "libsnmp.so.40": "libsnmp40t64",
    "libsodium.so.23": "libsodium23",
    "libsoftokn3.so": "libnss3",
    "libsonic.so.0": "libsonic0",
    "libsord-0.so.0": "libsord-0-0",
    "libsoup-3.0.so.0": "libsoup-3.0-0",
    "libsource-highlight.so.4": "libsource-highlight4t64",
    "libsoxr.so.0": "libsoxr0",
    "libspeechd.so.2": "libspeechd2",
    "libspeechd_module.so.0": "libspeechd-module0",
    "libspeex.so.1": "libspeex1",
    "libspeexdsp.so.1": "libspeexdsp1",
    "libspelling-1.so.2": "libspelling-1-2",
    "libsratom-0.so.0": "libsratom-0-0",
    "libssh.so.4": "libssh-4",
    "libssh2.so.1": "libssh2-1t64",
    "libssl3.so": "libnss3",
    "libsss_certmap.so.0": "libsss-certmap0",
    "libsss_idmap.so.0": "libsss-idmap0",
    "libsss_nss_idmap.so.0": "libsss-nss-idmap0",
    "libswresample.so.6": "libswresample6",
    "libswscale.so.9": "libswscale9",
    "libtag.so.2": "libtag2",
    "libtalloc.so.2": "libtalloc2",
    "libtdb.so.1": "libtdb1",
    "libteamdctl.so.0": "libteamdctl0",
    "libtevent.so.0": "libtevent0t64",
    "libthai.so.0": "libthai0",
    "libtheora.so.1": "libtheora1",
    "libtheoradec.so.2": "libtheoradec2",
    "libtheoraenc.so.2": "libtheoraenc2",
    "libtiff.so.6": "libtiff6",
    "libtinysparql-3.0.so.0": "libtinysparql-3.0-0",
    "libtotem-plparser.so.18": "libtotem-plparser18",
    "libtraceevent.so.1": "libtraceevent1",
    "libtracefs.so.1": "libtracefs1",
    "libtss2-rc.so.0": "libtss2-rc0t64",
    "libtss2-sys.so.1": "libtss2-sys1t64",
    "libtss2-tcti-cmd.so.0": "libtss2-tcti-cmd0t64",
    "libtss2-tcti-device.so.0": "libtss2-tcti-device0t64",
    "libtss2-tcti-mssim.so.0": "libtss2-tcti-mssim0t64",
    "libtss2-tcti-swtpm.so.0": "libtss2-tcti-swtpm0t64",
    "libtwolame.so.0": "libtwolame0",
    "libuchardet.so.0": "libuchardet0",
    "libudfread.so.3": "libudfread3",
    "libudisks2.so.0": "libudisks2-0",
    "libunibreak.so.6": "libunibreak6",
    "libunity-protocol-private.so.0": "libunity-protocol-private0",
    "libunity.so.9": "libunity9",
    "libunwind.so.8": "libunwind8",
    "libupower-glib.so.3": "libupower-glib3",
    "liburcu.so.8": "liburcu8t64",
    "libusb-1.0.so.0": "libusb-1.0-0",
    "libusbmuxd-2.0.so.7": "libusbmuxd-2.0-7",
    "libuv.so.1": "libuv1t64",
    "libv4l-mplane.so": "libv4l-0t64",
    "libv4l1.so.0": "libv4l-0t64",
    "libv4l2.so.0": "libv4l-0t64",
    "libv4l2tracer.so": "libv4l-0t64",
    "libv4lconvert.so.0": "libv4lconvert0t64",
    "libva-drm.so.2": "libva-drm2",
    "libva-x11.so.2": "libva-x11-2",
    "libva.so.2": "libva2",
    "libvdpau.so.1": "libvdpau1",
    "libvdpau_trace.so.1": "libvdpau1",
    "libvisual-0.4.so.0": "libvisual-0.4-0",
    "libvkd3d-shader.so.1": "libvkd3d-shader1",
    "libvkd3d-utils.so.1": "libvkd3d-utils1",
    "libvkd3d.so.1": "libvkd3d1",
    "libvolume_key.so.1": "libvolume-key1",
    "libvorbis.so.0": "libvorbis0a",
    "libvorbisenc.so.2": "libvorbisenc2",
    "libvorbisfile.so.3": "libvorbisfile3",
    "libvpl.so.2": "libvpl2",
    "libvpx.so.12": "libvpx12",
    "libvte-2.91-gtk4.so.0": "libvte-2.91-gtk4-0",
    "libvte-2.91.so.0": "libvte-2.91-0",
    "libvulkan.so.1": "libvulkan1",
    "libwacom.so.9": "libwacom9",
    "libwavpack.so.1": "libwavpack1",
    "libwayland-client.so.0": "libwayland-client0",
    "libwayland-cursor.so.0": "libwayland-cursor0",
    "libwayland-egl.so.1": "libwayland-egl1",
    "libwayland-server.so.0": "libwayland-server0",
    "libwbclient.so.0": "libwbclient0",
    "libwebkit2gtk-4.1.so.0": "libwebkit2gtk-4.1-0",
    "libwebkitgtk-6.0.so.4": "libwebkitgtk-6.0-4",
    "libwebp.so.7": "libwebp7",
    "libwebpdemux.so.2": "libwebpdemux2",
    "libwebpmux.so.3": "libwebpmux3",
    "libwebrtc-audio-processing-1.so.3": "libwebrtc-audio-processing-1-3",
    "libwhoopsie-preferences.so.0": "libwhoopsie-preferences0",
    "libwhoopsie.so.0": "libwhoopsie0",
    "libwireplumber-0.5.so.0": "libwireplumber-0.5-0",
    "libwmf-0.2.so.7": "libwmf-0.2-7",
    "libwmflite-0.2.so.7": "libwmflite-0.2-7",
    "libwnck-3.so.0": "libwnck-3-0",
    "libx11_plugin.so": "libcaca0",
    "libx11_plugin.so.0": "libcaca0",
    "libx264.so.165": "libx264-165",
    "libx265.so.215": "libx265-215",
    "libxcb-dri3.so.0": "libxcb-dri3-0",
    "libxcb-glx.so.0": "libxcb-glx0",
    "libxcb-present.so.0": "libxcb-present0",
    "libxcb-randr.so.0": "libxcb-randr0",
    "libxcb-render.so.0": "libxcb-render0",
    "libxcb-res.so.0": "libxcb-res0",
    "libxcb-shape.so.0": "libxcb-shape0",
    "libxcb-shm.so.0": "libxcb-shm0",
    "libxcb-sync.so.1": "libxcb-sync1",
    "libxcb-util.so.1": "libxcb-util1",
    "libxcb-xfixes.so.0": "libxcb-xfixes0",
    "libxcb.so.1": "libxcb1",
    "libxcvt.so.0": "libxcvt0",
    "libxkbfile.so.1": "libxkbfile1",
    "libxkbregistry.so.0": "libxkbregistry0",
    "libxml2.so.16": "libxml2-16",
    "libxmlb.so.2": "libxmlb2",
    "libxshmfence.so.1": "libxshmfence1",
    "libxvidcore.so.4": "libxvidcore4",
    "libyelp-1.so.0": "libyelp-1-0",
    "libzimg.so.2": "libzimg2",
    "libzip.so.5": "libzip5",
    "libzix-0.so.0": "libzix-0-0",
    "libzmq.so.5": "libzmq5",
    "libzvbi-chains.so.0": "libzvbi0t64",
    "libzvbi.so.0": "libzvbi0t64",
}
