#!/bin/sh
# libpulsecommon, BLAS and LAPACK sit in subdirectories nothing searches.
LIB="$SNAP/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH="$LIB/pulseaudio:$LIB/blas:$LIB/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
exec "$SNAP/yt-dlp_linux" "$@"
